### ISSUE TITLE
Quel programme ouvrir les fichiers ".mdj"?

### ISSUE THREAD

**Issue by jhon65496** [yoperiquoi/PlantCorner#1]
Quel programme ouvrir les fichiers **.mdj**?

**Fichiers ..\Conception\:**
  - Diagramme de paquetages.mdj;
  - Diagramme de séquence.mdj;
  - Diagrammes de classes et paquetages.mdj.

**Comment by yoperiquoi** [comment]
Bonjour c'est [StartUML](https://staruml.io/) une application utilisé pour créer des diagrammes UML.

**Comment by jhon65496** [comment]
@yoperiquoi 
Merci pour la réponse.
Avez-vous la possibilité de les convertir en Sparx_Systems_Enterprise_Architect_15.2?

**Comment by jhon65496** [comment]
@yoperiquoi 
J'apprends C#.
J'apprends Master-Detail.
Avez-vous un exemple Master-Detail plus simple?
Votre exemple 'PlantCorner' est compliqué pour moi.
Merci.

**Comment by yoperiquoi** [comment]
Il n'est pas possible de convertir les fichiers .mdj à ma connaissance, ils sont exclusif à StarUML.
Pour commencer vous devriez commencer par comprendre la notion de [binding](https://learn.microsoft.com/fr-fr/dotnet/desktop/wpf/data/how-to-use-the-master-detail-pattern-with-hierarchical-data?view=netframeworkdesktop-4.8).

**Comment by jhon65496** [comment]
@yoperiquoi 
Merci.... Désolé de vous prendre du temps..
C'est trop simple ))
Ce lien montre un exemple où toutes les listes sont dans une seule fenêtre.

Je pensais que s'il y avait beaucoup de champs, alors probablement les listes doivent être extraites dans un UserControl séparé.

Ensuite, la question se pose: comment tout organiser?
Peut-être que dans votre pratique, un tel exemple était?

Si en détail, alors je le vois comme ceci:
- Fenêtre principale
- Master: ListUserControl
- Detail: FormUserControl

En d'autres termes: (MainWindow(ListUserControl)(FormUserControl)).
